# Generated by Django 6.0.4 on 2026-05-03 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('location_id', models.CharField(max_length=50)),
                ('leave_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SYNC_ERROR', 'Sync Error')], default='PENDING', max_length=20)),
                ('hcm_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='timeoff_manager.employeeprofile')),
            ],
        ),
    ]
